import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import Form from "../components/elements/Form";
import Error from "../components/elements/Error";
import Section from "../components/containers/Section";
export default function Home() {
  const router = useRouter();
  const [error, setError] = useState(false);
  const [inputValue, setInputValue] = useState("");

  const onChange = (e) => {
    setInputValue(e.target.value);
  };
  const handleSubmit = (e) => {
    e.preventDefault();
    inputValue === "" ? setError(true) : router.push(`/search/${inputValue}`);
  };

  return (
    <>
      <Head>
        <title>Salud y Nutrición</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section title="Buscar de Articulos.">
        <Form change={onChange} submit={handleSubmit} />

        {error && (
          <Error
            text="Error: Necesitas escribir una búsqueda"
            notfound={false}
          />
        )}
      </Section>
    </>
  );
}
