import Head from "next/head";
import Search from "../components/elements/Search";
import Section from "../components/containers/Section";
export default function Home() {
  return (
    <>
      <Head>
        <title>Salud y Nutrición</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section>
        <Search />
      </Section>
    </>
  );
}
